wallpaper {
    monitor = DP-1
    path = /home/emmad/Pictures/Wallpapers/Paintings Col./Charles Dewolf Brownell: Sky - Northern Cuba.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = /home/emmad/Pictures/Wallpapers/Paintings Col./Skies.jpeg
}

splash = false